CREATE TABLE IF NOT EXISTS public.board
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    author text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT pk_board PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.line
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    geom geometry(LineString,4326),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_line PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.point
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    geom geometry(Point,4326),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT pk_point PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.polygon
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    geom geometry(Polygon,4326),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_polygon PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.visit_count
(
    id bigint NOT NULL DEFAULT 1,
    visit_count bigint NOT NULL,
    CONSTRAINT visit_count_pkey PRIMARY KEY (id)
    );

